# Generated by Django 2.1.1 on 2018-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.IntegerField(unique=True)),
                ('student_gpa', models.FloatField()),
                ('student_year', models.IntegerField()),
                ('student_class', models.IntegerField()),
                ('student_exam', models.CharField(max_length=20)),
            ],
        ),
    ]
