# Generated by Django 2.1.1 on 2018-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scorerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_wise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(unique=True)),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
    ]
