# Generated by Django 2.1.1 on 2018-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_class_wise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gurdian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gurdian_name', models.CharField(max_length=50)),
                ('gurdian_gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50)),
                ('gurdian_age', models.IntegerField()),
                ('gurdian_phone', models.IntegerField()),
            ],
        ),
    ]
