# Generated by Django 2.1.1 on 2018-10-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_gurdian'),
    ]

    operations = [
        migrations.AddField(
            model_name='studeninfo',
            name='guard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Gurdian'),
        ),
        migrations.AlterField(
            model_name='gurdian',
            name='gurdian_phone',
            field=models.IntegerField(unique=True),
        ),
    ]
