# Generated by Django 2.1.1 on 2018-10-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studeninfo_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurdian',
            name='id_gurdian',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
