# Generated by Django 2.1.1 on 2018-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distric_name', models.CharField(max_length=100)),
                ('distric_area', models.IntegerField()),
                ('distric_population', models.IntegerField()),
            ],
        ),
    ]
