# Generated by Django 2.1.1 on 2018-10-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50)),
            ],
        ),
    ]
